// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEfkTpDE4YCpikWONV4aBAs_Qtf5NkBNY',
    appId: '1:27585004336:web:bab5c45cf4e78dab773ef5',
    messagingSenderId: '27585004336',
    projectId: 'fakestore-c4aaf',
    authDomain: 'fakestore-c4aaf.firebaseapp.com',
    storageBucket: 'fakestore-c4aaf.appspot.com',
    measurementId: 'G-9X942ENSPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOT77fsIqSwAffafaeIwH7-MthM-bEIf8',
    appId: '1:27585004336:android:9b0b2d597fd882f9773ef5',
    messagingSenderId: '27585004336',
    projectId: 'fakestore-c4aaf',
    storageBucket: 'fakestore-c4aaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGazfV59APugk7HeNTu_jl0WKCsCU0yKA',
    appId: '1:27585004336:ios:ca787a87d522accd773ef5',
    messagingSenderId: '27585004336',
    projectId: 'fakestore-c4aaf',
    storageBucket: 'fakestore-c4aaf.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGazfV59APugk7HeNTu_jl0WKCsCU0yKA',
    appId: '1:27585004336:ios:ca787a87d522accd773ef5',
    messagingSenderId: '27585004336',
    projectId: 'fakestore-c4aaf',
    storageBucket: 'fakestore-c4aaf.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEfkTpDE4YCpikWONV4aBAs_Qtf5NkBNY',
    appId: '1:27585004336:web:4f368f02f9028293773ef5',
    messagingSenderId: '27585004336',
    projectId: 'fakestore-c4aaf',
    authDomain: 'fakestore-c4aaf.firebaseapp.com',
    storageBucket: 'fakestore-c4aaf.appspot.com',
    measurementId: 'G-YWMFQ2Q0KC',
  );
}
